### ISSUE TITLE
jemalloc 5.1.0 causing problems in heroku deploys release phase

### ISSUE THREAD

**Issue by concept47** [gaffneyc/heroku-buildpack-jemalloc#3] opened 2018-08-23 10:42 UTC
Since the change of version of jemalloc, we've started getting failures in the release phase of our heroku deploys that look like this

      rake aborted!
      JSON::ParserError: 765: unexpected token at 'node[29]: pthread_create: Invalid argument
      ["ok"]'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:68:in `extract_result'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:14:in `initialize'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
      /app/vendor/bundle/ruby/2.5.0/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'
      /app/vendor/bundle/ruby/2.5.0/gems/uglifier-4.1.10/lib/uglifier.rb:154:in `initialize'
      /app/config/environments/staging.rb:21:in `new'
      /app/config/environments/staging.rb:21:in `block in <main>'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/railtie.rb:209:in `instance_eval'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/railtie.rb:209:in `configure'
      /app/config/environments/staging.rb:1:in `<main>'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `block in require_with_bootsnap_lfi'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18:in `require_with_bootsnap_lfi'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:600:in `block (2 levels) in <class:Engine>'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:599:in `each'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/engine.rb:599:in `block in <class:Engine>'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `instance_exec'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `run'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:55:in `block in run_initializers'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `each'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `tsort_each_child'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/initializable.rb:54:in `run_initializers'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/application.rb:352:in `initialize!'
      /app/config/environment.rb:5:in `<main>'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:19:in `block in require_with_bootsnap_lfi'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:18:in `require_with_bootsnap_lfi'
      /app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:27:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `block in require'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
      /app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:293:in `require'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/application.rb:328:in `require_environment!'
      /app/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/application.rb:448:in `block in run_tasks_blocks'
      /app/vendor/bundle/ruby/2.5.0/gems/bugsnag-5.0.1/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'
      Tasks: TOP => db:migrate => environment
      (See full trace by running task with --trace)

The line in question in staging.rb that seems to fail is this one

         config.assets.js_compressor = Uglifier.new(harmony: true)

All our deploys with the jemalloc buildpack removed work just fine. (Figured this because our review apps don't use jemalloc, but it seemed that we had to run 

    heroku plugins:install heroku-repo
    heroku repo:purge_cache

To get it to work.

**Comment by concept47** [comment] 2018-08-23 20:35
https://github.com/jemalloc/jemalloc/issues/1313#issuecomment-415556057

**Comment by concept47** [comment] 2018-09-04 20:46
It worked a treat @gaffneyc. Thanks!

**Comment by gaffneyc** [comment] 2018-09-05 18:14
I'm considering reverting the change to make 5.1.0 the default. If you've run into this then 👍 this comment and I'll take that into consideration. I hate to move backwards but I also don't want to break things for people.

**Comment by jvdp** [comment] 2018-11-19 16:54
@gaffneyc I get a problem after release (running migrations) with jemalloc enabled, even with 5.0.1, on the heroku-16 stack. I'll experiment with other versions.

**Comment by gaffneyc** [comment] 2018-11-19 17:02
@jvdp Can you give some specifics on the problem you're seeing? For example, are you getting a stack trace, memory usage is going up, or response times are worse?

**Comment by gaffneyc** [comment] 2018-11-19 17:38
@jvdp The issue itself is with NodeJS (being called through ExecJS). I haven't had a chance to dig into the problem with Node but there are two things worth experimenting with. If you're seeing it on 5.0.1 then that's a new issue we haven't seen before (make sure you're pushing a code change as just changing JEMALLOC_VERSION isn't enough since jemalloc is baked into the slug).

1. Upgrade NodeJS
The default version for Rails applications on Heroku is 8.10.0 it's possible the issue has been fixed in a newer version of Node. You might be able to use therubyracer or mini_racer to get a newer version of node for testing. Otherwise you'll probably want to add the nodejs buildpack and use it to configure the node version.

2. Use jemalloc.sh
Use the [per dyno](https://github.com/gaffneyc/heroku-buildpack-jemalloc#per-dyno) config for jemalloc where you disable it globally (JEMALLOC_ENABLED=false) then add `jemalloc.sh` at the beginning of your web and (maybe) worker lines. This will disable jemalloc when running migrations but use it to run the application.

**Comment by jvdp** [comment] 2018-11-20 12:39
@gaffneyc thanks for the pointers! I think I wasn't actually running 5.0.1, I've retried with a code change after setting the version and now it seems to work OK!

**Comment by adamlogic** [comment] 2018-11-21 17:34
> The default version for Rails applications on Heroku is 8.10.0 it's possible the issue has been fixed in a newer version of Node. You might be able to use therubyracer or mini_racer to get a newer version of node for testing. Otherwise you'll probably want to add the nodejs buildpack and use it to configure the node version.

Just heads-up that I ran into this same issue using the nodejs buildpack and Node 9.5.0. `JEMALLOC_VERSION=5.0.1` fixed it. 🤷‍♂️

**Comment by gaffneyc** [comment] 2019-05-07 19:21
Has any one run into this issue recently? I tried to reproduce it a couples months ago and wasn't able to. Also, several things have changed in the months since the issue was first opened:
- [Ruby apps now default to Node 10.14.1](https://devcenter.heroku.com/changelog-items/1543)
- I've rebuilt the jemalloc 5.1.0 builds in linux with updated build containers from Heroku
- Jemalloc 5.2.0 has been released

Would one of you that has run into the issue be willing to try out Jemalloc 5.1.0 again? Or even [kick the tires on jemalloc 5.2.0](https://github.com/gaffneyc/heroku-buildpack-jemalloc/issues/11).

**Comment by ianwremmel** [comment] 2019-06-17 20:30
@gaffneyc I just ran into it with the default version today. Setting 5.0.1 fixed it.

```
  "engines": {
    "node": "10.13.0",
    "npm": "6.4.1",
    "yarn": "1.15.2"
  },
```

```
 "stack": "heroku-16",
  "buildpacks": [
    {
      "url": "https://github.com/gaffneyc/heroku-buildpack-jemalloc.git"
    },
    {
      "url": "heroku/nodejs"
    },
    {
      "url": "heroku/ruby"
    },
    {
      "url": "heroku-community/awscli"
    },
    {
      "url": "heroku-community/cli"
    }
  ]
```


This was the line in our code that threw, if that helps:
```
config.assets.js_compressor = Uglifier.new(harmony: true)
```

**Comment by gaffneyc** [comment] 2019-06-17 20:33
@ianwremmel Would you be able to give jemalloc 5.2.0 a try? It's looking like it _might_ be an issue with the Heroku 16 stack

**Comment by ianwremmel** [comment] 2019-06-17 20:38
trying it now

**Comment by ianwremmel** [comment] 2019-06-17 21:45
same problem with 5.2.0

**Comment by gaffneyc** [comment] 2019-06-18 13:36
@ianwremmel Awesome, thank you for testing it!

**Comment by gaffneyc** [comment] 2019-06-23 15:57
I've been able to reproduce the issue and I've [created a minimal test repository for it](https://github.com/gaffneyc/heroku-buildpack-jemalloc-issue-3) if anyone wants to try to solve it.

I've done some initial digging and it appears the issue is fixed on the `heroku-18` stack _or_ when using NodeJS `>= 12.0.0` on heroku-16 (or cedar-14).

| | cedar-14 | heroku-16 | heroku-18 |
| --- | --- | --- | --- |
| Node 10.13.0 | ❌ | ❌ | ✅ |
| Node 10.14.1 (Rails Default) | ❌ | ❌ | ✅ |
| Node 10.16.0 | ❌ | ❌ | ✅ |
| Node 12.4.0| ✅ | ✅ | ✅ |

I've run a bisect on jemalloc and this appears to be the commit that introduced the issue:
https://github.com/jemalloc/jemalloc/commit/9c0549007dcb64f4ff35d37390a9a6a8d3cea880

I am going to experiment with configure options to see if we can get builds working for cedar-14 and heroku-16. Since the problem will effectively go away as people move to Heroku 18 or newer versions of Node I'm not sure what else could be done.

**Comment by ianwremmel** [comment] 2019-06-24 20:06
@gaffneyc thanks for the update! We're looking to move to Heroku-18 in the coming weeks, so I think simply running on the older version is perfectly fine for us for the time being.

**Comment by gaffneyc** [comment] 2019-10-02 20:00
After more research it looks like it was fixed in 12.4.0 with [this commit](https://github.com/nodejs/node/pull/27855) and is triggered by thread stack size. Annoyingly, NodeJS is [printing the message](https://github.com/bnoordhuis/io.js/blob/ee68f56f4ef344635da8da5234c980fe22f02816/src/inspector_agent.cc#L141) that is breaking Uglifier.

Unfortunately this looking to be an issue in NodeJS (which has been fixed) that happens to be triggered by something in jemalloc. I've tested a number of build configs with jemalloc and none of them have addressed the issue.

Unfortunately I think the "fix" is to document the issue in the README and recommend folks use one of: Heroku 18, NodeJS 12.4.0+, or jemalloc 5.0.1 (in that order).

**Comment by gaffneyc** [comment] 2020-06-23 18:58
Heroku should be updating Ruby apps to use Node 12.16.2 by default sometime soon which should close this out once and for all.

Initial release yesterday (June 22nd) that was rolled back: https://devcenter.herokuapp.com/changelog-items/1818

**Comment by gaffneyc** [comment] 2020-07-14 18:23
Heroku finally rolled out the upgrade to Node 12.16.2 for Rails apps for all of their stacks. That should mean this is finally fixed for good (unless of course you're pinned to an _old_ version of NodeJS with the NodeJS buildpack).

https://devcenter.herokuapp.com/changelog-items/1825

**Closed by gaffneyc** 2020-07-14 18:23 UTC
